// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package object

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// DeleteObjectURL generates an URL for the delete object operation
type DeleteObjectURL struct {
	BucketName string

	AllVersions        *bool
	Bypass             *bool
	NonCurrentVersions *bool
	Prefix             string
	Recursive          *bool
	VersionID          *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteObjectURL) WithBasePath(bp string) *DeleteObjectURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteObjectURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *DeleteObjectURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/buckets/{bucket_name}/objects"

	bucketName := o.BucketName
	if bucketName != "" {
		_path = strings.Replace(_path, "{bucket_name}", bucketName, -1)
	} else {
		return nil, errors.New("bucketName is required on DeleteObjectURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var allVersionsQ string
	if o.AllVersions != nil {
		allVersionsQ = swag.FormatBool(*o.AllVersions)
	}
	if allVersionsQ != "" {
		qs.Set("all_versions", allVersionsQ)
	}

	var bypassQ string
	if o.Bypass != nil {
		bypassQ = swag.FormatBool(*o.Bypass)
	}
	if bypassQ != "" {
		qs.Set("bypass", bypassQ)
	}

	var nonCurrentVersionsQ string
	if o.NonCurrentVersions != nil {
		nonCurrentVersionsQ = swag.FormatBool(*o.NonCurrentVersions)
	}
	if nonCurrentVersionsQ != "" {
		qs.Set("non_current_versions", nonCurrentVersionsQ)
	}

	prefixQ := o.Prefix
	if prefixQ != "" {
		qs.Set("prefix", prefixQ)
	}

	var recursiveQ string
	if o.Recursive != nil {
		recursiveQ = swag.FormatBool(*o.Recursive)
	}
	if recursiveQ != "" {
		qs.Set("recursive", recursiveQ)
	}

	var versionIDQ string
	if o.VersionID != nil {
		versionIDQ = *o.VersionID
	}
	if versionIDQ != "" {
		qs.Set("version_id", versionIDQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *DeleteObjectURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *DeleteObjectURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *DeleteObjectURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on DeleteObjectURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on DeleteObjectURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *DeleteObjectURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
