// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package object

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openstor/console/models"
)

// DownloadObjectHandlerFunc turns a function with the right signature into a download object handler
type DownloadObjectHandlerFunc func(DownloadObjectParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DownloadObjectHandlerFunc) Handle(params DownloadObjectParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DownloadObjectHandler interface for that can handle valid download object params
type DownloadObjectHandler interface {
	Handle(DownloadObjectParams, *models.Principal) middleware.Responder
}

// NewDownloadObject creates a new http.Handler for the download object operation
func NewDownloadObject(ctx *middleware.Context, handler DownloadObjectHandler) *DownloadObject {
	return &DownloadObject{Context: ctx, Handler: handler}
}

/*
	DownloadObject swagger:route GET /buckets/{bucket_name}/objects/download Object downloadObject

Download Object
*/
type DownloadObject struct {
	Context *middleware.Context
	Handler DownloadObjectHandler
}

func (o *DownloadObject) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDownloadObjectParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
