// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package object

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openstor/console/models"
)

// ListObjectsHandlerFunc turns a function with the right signature into a list objects handler
type ListObjectsHandlerFunc func(ListObjectsParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn ListObjectsHandlerFunc) Handle(params ListObjectsParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// ListObjectsHandler interface for that can handle valid list objects params
type ListObjectsHandler interface {
	Handle(ListObjectsParams, *models.Principal) middleware.Responder
}

// NewListObjects creates a new http.Handler for the list objects operation
func NewListObjects(ctx *middleware.Context, handler ListObjectsHandler) *ListObjects {
	return &ListObjects{Context: ctx, Handler: handler}
}

/*
	ListObjects swagger:route GET /buckets/{bucket_name}/objects Object listObjects

List Objects
*/
type ListObjects struct {
	Context *middleware.Context
	Handler ListObjectsHandler
}

func (o *ListObjects) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListObjectsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
