// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package object

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openstor/console/models"
)

// PostBucketsBucketNameObjectsUploadOKCode is the HTTP code returned for type PostBucketsBucketNameObjectsUploadOK
const PostBucketsBucketNameObjectsUploadOKCode int = 200

/*
PostBucketsBucketNameObjectsUploadOK A successful response.

swagger:response postBucketsBucketNameObjectsUploadOK
*/
type PostBucketsBucketNameObjectsUploadOK struct {
}

// NewPostBucketsBucketNameObjectsUploadOK creates PostBucketsBucketNameObjectsUploadOK with default headers values
func NewPostBucketsBucketNameObjectsUploadOK() *PostBucketsBucketNameObjectsUploadOK {

	return &PostBucketsBucketNameObjectsUploadOK{}
}

// WriteResponse to the client
func (o *PostBucketsBucketNameObjectsUploadOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*
PostBucketsBucketNameObjectsUploadDefault Generic error response.

swagger:response postBucketsBucketNameObjectsUploadDefault
*/
type PostBucketsBucketNameObjectsUploadDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewPostBucketsBucketNameObjectsUploadDefault creates PostBucketsBucketNameObjectsUploadDefault with default headers values
func NewPostBucketsBucketNameObjectsUploadDefault(code int) *PostBucketsBucketNameObjectsUploadDefault {
	if code <= 0 {
		code = 500
	}

	return &PostBucketsBucketNameObjectsUploadDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post buckets bucket name objects upload default response
func (o *PostBucketsBucketNameObjectsUploadDefault) WithStatusCode(code int) *PostBucketsBucketNameObjectsUploadDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post buckets bucket name objects upload default response
func (o *PostBucketsBucketNameObjectsUploadDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post buckets bucket name objects upload default response
func (o *PostBucketsBucketNameObjectsUploadDefault) WithPayload(payload *models.APIError) *PostBucketsBucketNameObjectsUploadDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post buckets bucket name objects upload default response
func (o *PostBucketsBucketNameObjectsUploadDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBucketsBucketNameObjectsUploadDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
