// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package object

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openstor/console/models"
)

// PutObjectRestoreHandlerFunc turns a function with the right signature into a put object restore handler
type PutObjectRestoreHandlerFunc func(PutObjectRestoreParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PutObjectRestoreHandlerFunc) Handle(params PutObjectRestoreParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PutObjectRestoreHandler interface for that can handle valid put object restore params
type PutObjectRestoreHandler interface {
	Handle(PutObjectRestoreParams, *models.Principal) middleware.Responder
}

// NewPutObjectRestore creates a new http.Handler for the put object restore operation
func NewPutObjectRestore(ctx *middleware.Context, handler PutObjectRestoreHandler) *PutObjectRestore {
	return &PutObjectRestore{Context: ctx, Handler: handler}
}

/*
	PutObjectRestore swagger:route PUT /buckets/{bucket_name}/objects/restore Object putObjectRestore

Restore Object to a selected version
*/
type PutObjectRestore struct {
	Context *middleware.Context
	Handler PutObjectRestoreHandler
}

func (o *PutObjectRestore) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutObjectRestoreParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
