// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package object

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openstor/console/models"
)

// PutObjectTagsOKCode is the HTTP code returned for type PutObjectTagsOK
const PutObjectTagsOKCode int = 200

/*
PutObjectTagsOK A successful response.

swagger:response putObjectTagsOK
*/
type PutObjectTagsOK struct {
}

// NewPutObjectTagsOK creates PutObjectTagsOK with default headers values
func NewPutObjectTagsOK() *PutObjectTagsOK {

	return &PutObjectTagsOK{}
}

// WriteResponse to the client
func (o *PutObjectTagsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*
PutObjectTagsDefault Generic error response.

swagger:response putObjectTagsDefault
*/
type PutObjectTagsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewPutObjectTagsDefault creates PutObjectTagsDefault with default headers values
func NewPutObjectTagsDefault(code int) *PutObjectTagsDefault {
	if code <= 0 {
		code = 500
	}

	return &PutObjectTagsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put object tags default response
func (o *PutObjectTagsDefault) WithStatusCode(code int) *PutObjectTagsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put object tags default response
func (o *PutObjectTagsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put object tags default response
func (o *PutObjectTagsDefault) WithPayload(payload *models.APIError) *PutObjectTagsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put object tags default response
func (o *PutObjectTagsDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutObjectTagsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
