version: "2"
linters:
  default: none
  enable:
    - durationcheck
    - gocritic
    - gomodguard
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    goheader:
      values:
        regexp:
          copyright-holder: Copyright \(c\) (20\d\d\-20\d\d)|2021|({{year}})
      template-path: .license.tmpl
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: should have a package comment
      - path: (.+)\.go$
        text: comment on exported function
      - path: (.+)\.go$
        text: comment on exported type
      - path: (.+)\.go$
        text: should have comment
      - path: (.+)\.go$
        text: use leading k in Go names
      - path: (.+)\.go$
        text: comment on exported const
      # Ignore gofumpt formatting errors
      - path: (.+)\.go$
        text: File is not properly formatted
        linters:
          - gofumpt
      # Ignore misspell errors
      - path: (.+)\.go$
        text: wheter
        linters:
          - misspell
      # Ignore unused parameter errors
      - path: (.+)\.go$
        text: unused-parameter
        linters:
          - revive
      # Ignore staticcheck errors
      - path: (.+)\.go$
        text: QF1011
        linters:
          - staticcheck
      - path: (.+)\.go$
        text: ST1005
        linters:
          - staticcheck
      - path: (.+)\.go$
        text: QF1007
        linters:
          - staticcheck
      - path: (.+)\.go$
        text: QF1012
        linters:
          - staticcheck
      - path: (.+)\.go$
        text: ST1019
        linters:
          - staticcheck
      - path: (.+)\.go$
        text: QF1001
        linters:
          - staticcheck
      - path: (.+)\.go$
        text: QF1008
        linters:
          - staticcheck
      - path: (.+)\.go$
        text: SA1019
        linters:
          - staticcheck
      - path: (.+)\.go$
        text: QF1010
        linters:
          - staticcheck
      # Ignore var-naming errors
      - path: (.+)\.go$
        text: var-naming
        linters:
          - revive
    paths:
      - api/operations
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - api/operations
      - third_party$
      - builtin$
      - examples$
