// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package k_m_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openstor/console/models"
)

// KMSCreateKeyCreatedCode is the HTTP code returned for type KMSCreateKeyCreated
const KMSCreateKeyCreatedCode int = 201

/*
KMSCreateKeyCreated A successful response.

swagger:response kMSCreateKeyCreated
*/
type KMSCreateKeyCreated struct {
}

// NewKMSCreateKeyCreated creates KMSCreateKeyCreated with default headers values
func NewKMSCreateKeyCreated() *KMSCreateKeyCreated {

	return &KMSCreateKeyCreated{}
}

// WriteResponse to the client
func (o *KMSCreateKeyCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

/*
KMSCreateKeyDefault Generic error response.

swagger:response kMSCreateKeyDefault
*/
type KMSCreateKeyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewKMSCreateKeyDefault creates KMSCreateKeyDefault with default headers values
func NewKMSCreateKeyDefault(code int) *KMSCreateKeyDefault {
	if code <= 0 {
		code = 500
	}

	return &KMSCreateKeyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the k m s create key default response
func (o *KMSCreateKeyDefault) WithStatusCode(code int) *KMSCreateKeyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the k m s create key default response
func (o *KMSCreateKeyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the k m s create key default response
func (o *KMSCreateKeyDefault) WithPayload(payload *models.APIError) *KMSCreateKeyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the k m s create key default response
func (o *KMSCreateKeyDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *KMSCreateKeyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
