// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package k_m_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openstor/console/models"
)

// KMSStatusHandlerFunc turns a function with the right signature into a k m s status handler
type KMSStatusHandlerFunc func(KMSStatusParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn KMSStatusHandlerFunc) Handle(params KMSStatusParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// KMSStatusHandler interface for that can handle valid k m s status params
type KMSStatusHandler interface {
	Handle(KMSStatusParams, *models.Principal) middleware.Responder
}

// NewKMSStatus creates a new http.Handler for the k m s status operation
func NewKMSStatus(ctx *middleware.Context, handler KMSStatusHandler) *KMSStatus {
	return &KMSStatus{Context: ctx, Handler: handler}
}

/*
	KMSStatus swagger:route GET /kms/status KMS kMSStatus

KMS status
*/
type KMSStatus struct {
	Context *middleware.Context
	Handler KMSStatusHandler
}

func (o *KMSStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewKMSStatusParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
