// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openstor/console/models"
)

// NotificationEndpointListHandlerFunc turns a function with the right signature into a notification endpoint list handler
type NotificationEndpointListHandlerFunc func(NotificationEndpointListParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn NotificationEndpointListHandlerFunc) Handle(params NotificationEndpointListParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// NotificationEndpointListHandler interface for that can handle valid notification endpoint list params
type NotificationEndpointListHandler interface {
	Handle(NotificationEndpointListParams, *models.Principal) middleware.Responder
}

// NewNotificationEndpointList creates a new http.Handler for the notification endpoint list operation
func NewNotificationEndpointList(ctx *middleware.Context, handler NotificationEndpointListHandler) *NotificationEndpointList {
	return &NotificationEndpointList{Context: ctx, Handler: handler}
}

/*
	NotificationEndpointList swagger:route GET /admin/notification_endpoints Configuration notificationEndpointList

Returns a list of active notification endpoints
*/
type NotificationEndpointList struct {
	Context *middleware.Context
	Handler NotificationEndpointListHandler
}

func (o *NotificationEndpointList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewNotificationEndpointListParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
