// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openstor/console/models"
)

// SetConfigHandlerFunc turns a function with the right signature into a set config handler
type SetConfigHandlerFunc func(SetConfigParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn SetConfigHandlerFunc) Handle(params SetConfigParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// SetConfigHandler interface for that can handle valid set config params
type SetConfigHandler interface {
	Handle(SetConfigParams, *models.Principal) middleware.Responder
}

// NewSetConfig creates a new http.Handler for the set config operation
func NewSetConfig(ctx *middleware.Context, handler SetConfigHandler) *SetConfig {
	return &SetConfig{Context: ctx, Handler: handler}
}

/*
	SetConfig swagger:route PUT /configs/{name} Configuration setConfig

Set Configuration
*/
type SetConfig struct {
	Context *middleware.Context
	Handler SetConfigHandler
}

func (o *SetConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSetConfigParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
