// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package idp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openstor/console/models"
)

// GetConfigurationOKCode is the HTTP code returned for type GetConfigurationOK
const GetConfigurationOKCode int = 200

/*
GetConfigurationOK A successful response.

swagger:response getConfigurationOK
*/
type GetConfigurationOK struct {

	/*
	  In: Body
	*/
	Payload *models.IdpServerConfiguration `json:"body,omitempty"`
}

// NewGetConfigurationOK creates GetConfigurationOK with default headers values
func NewGetConfigurationOK() *GetConfigurationOK {

	return &GetConfigurationOK{}
}

// WithPayload adds the payload to the get configuration o k response
func (o *GetConfigurationOK) WithPayload(payload *models.IdpServerConfiguration) *GetConfigurationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get configuration o k response
func (o *GetConfigurationOK) SetPayload(payload *models.IdpServerConfiguration) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigurationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetConfigurationDefault Generic error response.

swagger:response getConfigurationDefault
*/
type GetConfigurationDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewGetConfigurationDefault creates GetConfigurationDefault with default headers values
func NewGetConfigurationDefault(code int) *GetConfigurationDefault {
	if code <= 0 {
		code = 500
	}

	return &GetConfigurationDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get configuration default response
func (o *GetConfigurationDefault) WithStatusCode(code int) *GetConfigurationDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get configuration default response
func (o *GetConfigurationDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get configuration default response
func (o *GetConfigurationDefault) WithPayload(payload *models.APIError) *GetConfigurationDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get configuration default response
func (o *GetConfigurationDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigurationDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
