// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package idp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openstor/console/models"
)

// GetLDAPEntitiesHandlerFunc turns a function with the right signature into a get l d a p entities handler
type GetLDAPEntitiesHandlerFunc func(GetLDAPEntitiesParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetLDAPEntitiesHandlerFunc) Handle(params GetLDAPEntitiesParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetLDAPEntitiesHandler interface for that can handle valid get l d a p entities params
type GetLDAPEntitiesHandler interface {
	Handle(GetLDAPEntitiesParams, *models.Principal) middleware.Responder
}

// NewGetLDAPEntities creates a new http.Handler for the get l d a p entities operation
func NewGetLDAPEntities(ctx *middleware.Context, handler GetLDAPEntitiesHandler) *GetLDAPEntities {
	return &GetLDAPEntities{Context: ctx, Handler: handler}
}

/*
	GetLDAPEntities swagger:route POST /ldap-entities idp getLDAPEntities

Get LDAP Entities
*/
type GetLDAPEntities struct {
	Context *middleware.Context
	Handler GetLDAPEntitiesHandler
}

func (o *GetLDAPEntities) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetLDAPEntitiesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
