// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package idp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openstor/console/models"
)

// UpdateConfigurationOKCode is the HTTP code returned for type UpdateConfigurationOK
const UpdateConfigurationOKCode int = 200

/*
UpdateConfigurationOK A successful response.

swagger:response updateConfigurationOK
*/
type UpdateConfigurationOK struct {

	/*
	  In: Body
	*/
	Payload *models.SetIDPResponse `json:"body,omitempty"`
}

// NewUpdateConfigurationOK creates UpdateConfigurationOK with default headers values
func NewUpdateConfigurationOK() *UpdateConfigurationOK {

	return &UpdateConfigurationOK{}
}

// WithPayload adds the payload to the update configuration o k response
func (o *UpdateConfigurationOK) WithPayload(payload *models.SetIDPResponse) *UpdateConfigurationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update configuration o k response
func (o *UpdateConfigurationOK) SetPayload(payload *models.SetIDPResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateConfigurationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
UpdateConfigurationDefault Generic error response.

swagger:response updateConfigurationDefault
*/
type UpdateConfigurationDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewUpdateConfigurationDefault creates UpdateConfigurationDefault with default headers values
func NewUpdateConfigurationDefault(code int) *UpdateConfigurationDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateConfigurationDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update configuration default response
func (o *UpdateConfigurationDefault) WithStatusCode(code int) *UpdateConfigurationDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update configuration default response
func (o *UpdateConfigurationDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the update configuration default response
func (o *UpdateConfigurationDefault) WithPayload(payload *models.APIError) *UpdateConfigurationDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update configuration default response
func (o *UpdateConfigurationDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateConfigurationDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
