// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package idp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openstor/console/models"
)

// UpdateConfigurationHandlerFunc turns a function with the right signature into a update configuration handler
type UpdateConfigurationHandlerFunc func(UpdateConfigurationParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateConfigurationHandlerFunc) Handle(params UpdateConfigurationParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// UpdateConfigurationHandler interface for that can handle valid update configuration params
type UpdateConfigurationHandler interface {
	Handle(UpdateConfigurationParams, *models.Principal) middleware.Responder
}

// NewUpdateConfiguration creates a new http.Handler for the update configuration operation
func NewUpdateConfiguration(ctx *middleware.Context, handler UpdateConfigurationHandler) *UpdateConfiguration {
	return &UpdateConfiguration{Context: ctx, Handler: handler}
}

/*
	UpdateConfiguration swagger:route PUT /idp/{type}/{name} idp updateConfiguration

Update IDP Configuration
*/
type UpdateConfiguration struct {
	Context *middleware.Context
	Handler UpdateConfigurationHandler
}

func (o *UpdateConfiguration) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateConfigurationParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
