// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openstor/console/models"
)

// BulkUpdateUsersGroupsOKCode is the HTTP code returned for type BulkUpdateUsersGroupsOK
const BulkUpdateUsersGroupsOKCode int = 200

/*
BulkUpdateUsersGroupsOK A successful response.

swagger:response bulkUpdateUsersGroupsOK
*/
type BulkUpdateUsersGroupsOK struct {
}

// NewBulkUpdateUsersGroupsOK creates BulkUpdateUsersGroupsOK with default headers values
func NewBulkUpdateUsersGroupsOK() *BulkUpdateUsersGroupsOK {

	return &BulkUpdateUsersGroupsOK{}
}

// WriteResponse to the client
func (o *BulkUpdateUsersGroupsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*
BulkUpdateUsersGroupsDefault Generic error response.

swagger:response bulkUpdateUsersGroupsDefault
*/
type BulkUpdateUsersGroupsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewBulkUpdateUsersGroupsDefault creates BulkUpdateUsersGroupsDefault with default headers values
func NewBulkUpdateUsersGroupsDefault(code int) *BulkUpdateUsersGroupsDefault {
	if code <= 0 {
		code = 500
	}

	return &BulkUpdateUsersGroupsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the bulk update users groups default response
func (o *BulkUpdateUsersGroupsDefault) WithStatusCode(code int) *BulkUpdateUsersGroupsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the bulk update users groups default response
func (o *BulkUpdateUsersGroupsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the bulk update users groups default response
func (o *BulkUpdateUsersGroupsDefault) WithPayload(payload *models.APIError) *BulkUpdateUsersGroupsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the bulk update users groups default response
func (o *BulkUpdateUsersGroupsDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BulkUpdateUsersGroupsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
