// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openstor/console/models"
)

// CheckUserServiceAccountsHandlerFunc turns a function with the right signature into a check user service accounts handler
type CheckUserServiceAccountsHandlerFunc func(CheckUserServiceAccountsParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn CheckUserServiceAccountsHandlerFunc) Handle(params CheckUserServiceAccountsParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// CheckUserServiceAccountsHandler interface for that can handle valid check user service accounts params
type CheckUserServiceAccountsHandler interface {
	Handle(CheckUserServiceAccountsParams, *models.Principal) middleware.Responder
}

// NewCheckUserServiceAccounts creates a new http.Handler for the check user service accounts operation
func NewCheckUserServiceAccounts(ctx *middleware.Context, handler CheckUserServiceAccountsHandler) *CheckUserServiceAccounts {
	return &CheckUserServiceAccounts{Context: ctx, Handler: handler}
}

/*
	CheckUserServiceAccounts swagger:route POST /users/service-accounts User checkUserServiceAccounts

Check number of service accounts for each user specified
*/
type CheckUserServiceAccounts struct {
	Context *middleware.Context
	Handler CheckUserServiceAccountsHandler
}

func (o *CheckUserServiceAccounts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCheckUserServiceAccountsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
