// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"github.com/openstor/console/models"
)

// NewCheckUserServiceAccountsParams creates a new CheckUserServiceAccountsParams object
//
// There are no default values defined in the spec.
func NewCheckUserServiceAccountsParams() CheckUserServiceAccountsParams {

	return CheckUserServiceAccountsParams{}
}

// CheckUserServiceAccountsParams contains all the bound params for the check user service accounts operation
// typically these are obtained from a http.Request
//
// swagger:parameters CheckUserServiceAccounts
type CheckUserServiceAccountsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	SelectedUsers models.SelectedUsers
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCheckUserServiceAccountsParams() beforehand.
func (o *CheckUserServiceAccountsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.SelectedUsers
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("selectedUsers", "body", ""))
			} else {
				res = append(res, errors.NewParseError("selectedUsers", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.SelectedUsers = body
			}
		}
	} else {
		res = append(res, errors.Required("selectedUsers", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
