// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openstor/console/models"
)

// ListAUserServiceAccountsHandlerFunc turns a function with the right signature into a list a user service accounts handler
type ListAUserServiceAccountsHandlerFunc func(ListAUserServiceAccountsParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn ListAUserServiceAccountsHandlerFunc) Handle(params ListAUserServiceAccountsParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// ListAUserServiceAccountsHandler interface for that can handle valid list a user service accounts params
type ListAUserServiceAccountsHandler interface {
	Handle(ListAUserServiceAccountsParams, *models.Principal) middleware.Responder
}

// NewListAUserServiceAccounts creates a new http.Handler for the list a user service accounts operation
func NewListAUserServiceAccounts(ctx *middleware.Context, handler ListAUserServiceAccountsHandler) *ListAUserServiceAccounts {
	return &ListAUserServiceAccounts{Context: ctx, Handler: handler}
}

/*
	ListAUserServiceAccounts swagger:route GET /user/{name}/service-accounts User listAUserServiceAccounts

returns a list of service accounts for a user
*/
type ListAUserServiceAccounts struct {
	Context *middleware.Context
	Handler ListAUserServiceAccountsHandler
}

func (o *ListAUserServiceAccounts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListAUserServiceAccountsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
