// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openstor/console/models"
)

// UpdateUserGroupsOKCode is the HTTP code returned for type UpdateUserGroupsOK
const UpdateUserGroupsOKCode int = 200

/*
UpdateUserGroupsOK A successful response.

swagger:response updateUserGroupsOK
*/
type UpdateUserGroupsOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewUpdateUserGroupsOK creates UpdateUserGroupsOK with default headers values
func NewUpdateUserGroupsOK() *UpdateUserGroupsOK {

	return &UpdateUserGroupsOK{}
}

// WithPayload adds the payload to the update user groups o k response
func (o *UpdateUserGroupsOK) WithPayload(payload *models.User) *UpdateUserGroupsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update user groups o k response
func (o *UpdateUserGroupsOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateUserGroupsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
UpdateUserGroupsDefault Generic error response.

swagger:response updateUserGroupsDefault
*/
type UpdateUserGroupsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewUpdateUserGroupsDefault creates UpdateUserGroupsDefault with default headers values
func NewUpdateUserGroupsDefault(code int) *UpdateUserGroupsDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateUserGroupsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update user groups default response
func (o *UpdateUserGroupsDefault) WithStatusCode(code int) *UpdateUserGroupsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update user groups default response
func (o *UpdateUserGroupsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the update user groups default response
func (o *UpdateUserGroupsDefault) WithPayload(payload *models.APIError) *UpdateUserGroupsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update user groups default response
func (o *UpdateUserGroupsDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateUserGroupsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
