// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openstor/console/models"
)

// UpdateUserInfoOKCode is the HTTP code returned for type UpdateUserInfoOK
const UpdateUserInfoOKCode int = 200

/*
UpdateUserInfoOK A successful response.

swagger:response updateUserInfoOK
*/
type UpdateUserInfoOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewUpdateUserInfoOK creates UpdateUserInfoOK with default headers values
func NewUpdateUserInfoOK() *UpdateUserInfoOK {

	return &UpdateUserInfoOK{}
}

// WithPayload adds the payload to the update user info o k response
func (o *UpdateUserInfoOK) WithPayload(payload *models.User) *UpdateUserInfoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update user info o k response
func (o *UpdateUserInfoOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateUserInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
UpdateUserInfoDefault Generic error response.

swagger:response updateUserInfoDefault
*/
type UpdateUserInfoDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewUpdateUserInfoDefault creates UpdateUserInfoDefault with default headers values
func NewUpdateUserInfoDefault(code int) *UpdateUserInfoDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateUserInfoDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update user info default response
func (o *UpdateUserInfoDefault) WithStatusCode(code int) *UpdateUserInfoDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update user info default response
func (o *UpdateUserInfoDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the update user info default response
func (o *UpdateUserInfoDefault) WithPayload(payload *models.APIError) *UpdateUserInfoDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update user info default response
func (o *UpdateUserInfoDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateUserInfoDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
