// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package bucket

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openstor/console/models"
)

// DeleteRemoteBucketNoContentCode is the HTTP code returned for type DeleteRemoteBucketNoContent
const DeleteRemoteBucketNoContentCode int = 204

/*
DeleteRemoteBucketNoContent A successful response.

swagger:response deleteRemoteBucketNoContent
*/
type DeleteRemoteBucketNoContent struct {
}

// NewDeleteRemoteBucketNoContent creates DeleteRemoteBucketNoContent with default headers values
func NewDeleteRemoteBucketNoContent() *DeleteRemoteBucketNoContent {

	return &DeleteRemoteBucketNoContent{}
}

// WriteResponse to the client
func (o *DeleteRemoteBucketNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*
DeleteRemoteBucketDefault Generic error response.

swagger:response deleteRemoteBucketDefault
*/
type DeleteRemoteBucketDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewDeleteRemoteBucketDefault creates DeleteRemoteBucketDefault with default headers values
func NewDeleteRemoteBucketDefault(code int) *DeleteRemoteBucketDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteRemoteBucketDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete remote bucket default response
func (o *DeleteRemoteBucketDefault) WithStatusCode(code int) *DeleteRemoteBucketDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete remote bucket default response
func (o *DeleteRemoteBucketDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete remote bucket default response
func (o *DeleteRemoteBucketDefault) WithPayload(payload *models.APIError) *DeleteRemoteBucketDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete remote bucket default response
func (o *DeleteRemoteBucketDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteRemoteBucketDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
