// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package bucket

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openstor/console/models"
)

// DeleteBucketNoContentCode is the HTTP code returned for type DeleteBucketNoContent
const DeleteBucketNoContentCode int = 204

/*
DeleteBucketNoContent A successful response.

swagger:response deleteBucketNoContent
*/
type DeleteBucketNoContent struct {
}

// NewDeleteBucketNoContent creates DeleteBucketNoContent with default headers values
func NewDeleteBucketNoContent() *DeleteBucketNoContent {

	return &DeleteBucketNoContent{}
}

// WriteResponse to the client
func (o *DeleteBucketNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*
DeleteBucketDefault Generic error response.

swagger:response deleteBucketDefault
*/
type DeleteBucketDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewDeleteBucketDefault creates DeleteBucketDefault with default headers values
func NewDeleteBucketDefault(code int) *DeleteBucketDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteBucketDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete bucket default response
func (o *DeleteBucketDefault) WithStatusCode(code int) *DeleteBucketDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete bucket default response
func (o *DeleteBucketDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete bucket default response
func (o *DeleteBucketDefault) WithPayload(payload *models.APIError) *DeleteBucketDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete bucket default response
func (o *DeleteBucketDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBucketDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
