// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package bucket

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openstor/console/models"
)

// GetBucketReplicationHandlerFunc turns a function with the right signature into a get bucket replication handler
type GetBucketReplicationHandlerFunc func(GetBucketReplicationParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBucketReplicationHandlerFunc) Handle(params GetBucketReplicationParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetBucketReplicationHandler interface for that can handle valid get bucket replication params
type GetBucketReplicationHandler interface {
	Handle(GetBucketReplicationParams, *models.Principal) middleware.Responder
}

// NewGetBucketReplication creates a new http.Handler for the get bucket replication operation
func NewGetBucketReplication(ctx *middleware.Context, handler GetBucketReplicationHandler) *GetBucketReplication {
	return &GetBucketReplication{Context: ctx, Handler: handler}
}

/*
	GetBucketReplication swagger:route GET /buckets/{bucket_name}/replication Bucket getBucketReplication

Bucket Replication
*/
type GetBucketReplication struct {
	Context *middleware.Context
	Handler GetBucketReplicationHandler
}

func (o *GetBucketReplication) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetBucketReplicationParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
