// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package bucket

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openstor/console/models"
)

// GetBucketRewindHandlerFunc turns a function with the right signature into a get bucket rewind handler
type GetBucketRewindHandlerFunc func(GetBucketRewindParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBucketRewindHandlerFunc) Handle(params GetBucketRewindParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetBucketRewindHandler interface for that can handle valid get bucket rewind params
type GetBucketRewindHandler interface {
	Handle(GetBucketRewindParams, *models.Principal) middleware.Responder
}

// NewGetBucketRewind creates a new http.Handler for the get bucket rewind operation
func NewGetBucketRewind(ctx *middleware.Context, handler GetBucketRewindHandler) *GetBucketRewind {
	return &GetBucketRewind{Context: ctx, Handler: handler}
}

/*
	GetBucketRewind swagger:route GET /buckets/{bucket_name}/rewind/{date} Bucket getBucketRewind

Get objects in a bucket for a rewind date
*/
type GetBucketRewind struct {
	Context *middleware.Context
	Handler GetBucketRewindHandler
}

func (o *GetBucketRewind) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetBucketRewindParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
