// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package bucket

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openstor/console/models"
)

// ListRemoteBucketsOKCode is the HTTP code returned for type ListRemoteBucketsOK
const ListRemoteBucketsOKCode int = 200

/*
ListRemoteBucketsOK A successful response.

swagger:response listRemoteBucketsOK
*/
type ListRemoteBucketsOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListRemoteBucketsResponse `json:"body,omitempty"`
}

// NewListRemoteBucketsOK creates ListRemoteBucketsOK with default headers values
func NewListRemoteBucketsOK() *ListRemoteBucketsOK {

	return &ListRemoteBucketsOK{}
}

// WithPayload adds the payload to the list remote buckets o k response
func (o *ListRemoteBucketsOK) WithPayload(payload *models.ListRemoteBucketsResponse) *ListRemoteBucketsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list remote buckets o k response
func (o *ListRemoteBucketsOK) SetPayload(payload *models.ListRemoteBucketsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListRemoteBucketsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
ListRemoteBucketsDefault Generic error response.

swagger:response listRemoteBucketsDefault
*/
type ListRemoteBucketsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewListRemoteBucketsDefault creates ListRemoteBucketsDefault with default headers values
func NewListRemoteBucketsDefault(code int) *ListRemoteBucketsDefault {
	if code <= 0 {
		code = 500
	}

	return &ListRemoteBucketsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list remote buckets default response
func (o *ListRemoteBucketsDefault) WithStatusCode(code int) *ListRemoteBucketsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list remote buckets default response
func (o *ListRemoteBucketsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list remote buckets default response
func (o *ListRemoteBucketsDefault) WithPayload(payload *models.APIError) *ListRemoteBucketsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list remote buckets default response
func (o *ListRemoteBucketsDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListRemoteBucketsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
