// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package bucket

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openstor/console/models"
)

// PutBucketTagsHandlerFunc turns a function with the right signature into a put bucket tags handler
type PutBucketTagsHandlerFunc func(PutBucketTagsParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PutBucketTagsHandlerFunc) Handle(params PutBucketTagsParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PutBucketTagsHandler interface for that can handle valid put bucket tags params
type PutBucketTagsHandler interface {
	Handle(PutBucketTagsParams, *models.Principal) middleware.Responder
}

// NewPutBucketTags creates a new http.Handler for the put bucket tags operation
func NewPutBucketTags(ctx *middleware.Context, handler PutBucketTagsHandler) *PutBucketTags {
	return &PutBucketTags{Context: ctx, Handler: handler}
}

/*
	PutBucketTags swagger:route PUT /buckets/{bucket_name}/tags Bucket putBucketTags

Put Bucket's tags
*/
type PutBucketTags struct {
	Context *middleware.Context
	Handler PutBucketTagsHandler
}

func (o *PutBucketTags) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutBucketTagsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
