// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package bucket

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openstor/console/models"
)

// SetBucketRetentionConfigOKCode is the HTTP code returned for type SetBucketRetentionConfigOK
const SetBucketRetentionConfigOKCode int = 200

/*
SetBucketRetentionConfigOK A successful response.

swagger:response setBucketRetentionConfigOK
*/
type SetBucketRetentionConfigOK struct {
}

// NewSetBucketRetentionConfigOK creates SetBucketRetentionConfigOK with default headers values
func NewSetBucketRetentionConfigOK() *SetBucketRetentionConfigOK {

	return &SetBucketRetentionConfigOK{}
}

// WriteResponse to the client
func (o *SetBucketRetentionConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*
SetBucketRetentionConfigDefault Generic error response.

swagger:response setBucketRetentionConfigDefault
*/
type SetBucketRetentionConfigDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewSetBucketRetentionConfigDefault creates SetBucketRetentionConfigDefault with default headers values
func NewSetBucketRetentionConfigDefault(code int) *SetBucketRetentionConfigDefault {
	if code <= 0 {
		code = 500
	}

	return &SetBucketRetentionConfigDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the set bucket retention config default response
func (o *SetBucketRetentionConfigDefault) WithStatusCode(code int) *SetBucketRetentionConfigDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the set bucket retention config default response
func (o *SetBucketRetentionConfigDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the set bucket retention config default response
func (o *SetBucketRetentionConfigDefault) WithPayload(payload *models.APIError) *SetBucketRetentionConfigDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the set bucket retention config default response
func (o *SetBucketRetentionConfigDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SetBucketRetentionConfigDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
