// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package bucket

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openstor/console/models"
)

// SetBucketQuotaOKCode is the HTTP code returned for type SetBucketQuotaOK
const SetBucketQuotaOKCode int = 200

/*
SetBucketQuotaOK A successful response.

swagger:response setBucketQuotaOK
*/
type SetBucketQuotaOK struct {

	/*
	  In: Body
	*/
	Payload *models.Bucket `json:"body,omitempty"`
}

// NewSetBucketQuotaOK creates SetBucketQuotaOK with default headers values
func NewSetBucketQuotaOK() *SetBucketQuotaOK {

	return &SetBucketQuotaOK{}
}

// WithPayload adds the payload to the set bucket quota o k response
func (o *SetBucketQuotaOK) WithPayload(payload *models.Bucket) *SetBucketQuotaOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the set bucket quota o k response
func (o *SetBucketQuotaOK) SetPayload(payload *models.Bucket) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SetBucketQuotaOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
SetBucketQuotaDefault Generic error response.

swagger:response setBucketQuotaDefault
*/
type SetBucketQuotaDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewSetBucketQuotaDefault creates SetBucketQuotaDefault with default headers values
func NewSetBucketQuotaDefault(code int) *SetBucketQuotaDefault {
	if code <= 0 {
		code = 500
	}

	return &SetBucketQuotaDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the set bucket quota default response
func (o *SetBucketQuotaDefault) WithStatusCode(code int) *SetBucketQuotaDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the set bucket quota default response
func (o *SetBucketQuotaDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the set bucket quota default response
func (o *SetBucketQuotaDefault) WithPayload(payload *models.APIError) *SetBucketQuotaDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the set bucket quota default response
func (o *SetBucketQuotaDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SetBucketQuotaDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
