// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package bucket

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openstor/console/models"
)

// SetBucketRetentionConfigHandlerFunc turns a function with the right signature into a set bucket retention config handler
type SetBucketRetentionConfigHandlerFunc func(SetBucketRetentionConfigParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn SetBucketRetentionConfigHandlerFunc) Handle(params SetBucketRetentionConfigParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// SetBucketRetentionConfigHandler interface for that can handle valid set bucket retention config params
type SetBucketRetentionConfigHandler interface {
	Handle(SetBucketRetentionConfigParams, *models.Principal) middleware.Responder
}

// NewSetBucketRetentionConfig creates a new http.Handler for the set bucket retention config operation
func NewSetBucketRetentionConfig(ctx *middleware.Context, handler SetBucketRetentionConfigHandler) *SetBucketRetentionConfig {
	return &SetBucketRetentionConfig{Context: ctx, Handler: handler}
}

/*
	SetBucketRetentionConfig swagger:route PUT /buckets/{bucket_name}/retention Bucket setBucketRetentionConfig

Set Bucket's retention config
*/
type SetBucketRetentionConfig struct {
	Context *middleware.Context
	Handler SetBucketRetentionConfigHandler
}

func (o *SetBucketRetentionConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSetBucketRetentionConfigParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
