// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openstor/console/models"
)

// RestartServiceNoContentCode is the HTTP code returned for type RestartServiceNoContent
const RestartServiceNoContentCode int = 204

/*
RestartServiceNoContent A successful response.

swagger:response restartServiceNoContent
*/
type RestartServiceNoContent struct {
}

// NewRestartServiceNoContent creates RestartServiceNoContent with default headers values
func NewRestartServiceNoContent() *RestartServiceNoContent {

	return &RestartServiceNoContent{}
}

// WriteResponse to the client
func (o *RestartServiceNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*
RestartServiceDefault Generic error response.

swagger:response restartServiceDefault
*/
type RestartServiceDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewRestartServiceDefault creates RestartServiceDefault with default headers values
func NewRestartServiceDefault(code int) *RestartServiceDefault {
	if code <= 0 {
		code = 500
	}

	return &RestartServiceDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the restart service default response
func (o *RestartServiceDefault) WithStatusCode(code int) *RestartServiceDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the restart service default response
func (o *RestartServiceDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the restart service default response
func (o *RestartServiceDefault) WithPayload(payload *models.APIError) *RestartServiceDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the restart service default response
func (o *RestartServiceDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RestartServiceDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
