// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openstor/console/models"
)

// RestartServiceHandlerFunc turns a function with the right signature into a restart service handler
type RestartServiceHandlerFunc func(RestartServiceParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn RestartServiceHandlerFunc) Handle(params RestartServiceParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// RestartServiceHandler interface for that can handle valid restart service params
type RestartServiceHandler interface {
	Handle(RestartServiceParams, *models.Principal) middleware.Responder
}

// NewRestartService creates a new http.Handler for the restart service operation
func NewRestartService(ctx *middleware.Context, handler RestartServiceHandler) *RestartService {
	return &RestartService{Context: ctx, Handler: handler}
}

/*
	RestartService swagger:route POST /service/restart Service restartService

Restart Service
*/
type RestartService struct {
	Context *middleware.Context
	Handler RestartServiceHandler
}

func (o *RestartService) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewRestartServiceParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
