// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openstor/console/models"
)

// ArnListHandlerFunc turns a function with the right signature into a arn list handler
type ArnListHandlerFunc func(ArnListParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn ArnListHandlerFunc) Handle(params ArnListParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// ArnListHandler interface for that can handle valid arn list params
type ArnListHandler interface {
	Handle(ArnListParams, *models.Principal) middleware.Responder
}

// NewArnList creates a new http.Handler for the arn list operation
func NewArnList(ctx *middleware.Context, handler ArnListHandler) *ArnList {
	return &ArnList{Context: ctx, Handler: handler}
}

/*
	ArnList swagger:route GET /admin/arns System arnList

Returns a list of active ARNs in the instance
*/
type ArnList struct {
	Context *middleware.Context
	Handler ArnListHandler
}

func (o *ArnList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewArnListParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
