// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openstor/console/models"
)

// DashboardWidgetDetailsOKCode is the HTTP code returned for type DashboardWidgetDetailsOK
const DashboardWidgetDetailsOKCode int = 200

/*
DashboardWidgetDetailsOK A successful response.

swagger:response dashboardWidgetDetailsOK
*/
type DashboardWidgetDetailsOK struct {

	/*
	  In: Body
	*/
	Payload *models.WidgetDetails `json:"body,omitempty"`
}

// NewDashboardWidgetDetailsOK creates DashboardWidgetDetailsOK with default headers values
func NewDashboardWidgetDetailsOK() *DashboardWidgetDetailsOK {

	return &DashboardWidgetDetailsOK{}
}

// WithPayload adds the payload to the dashboard widget details o k response
func (o *DashboardWidgetDetailsOK) WithPayload(payload *models.WidgetDetails) *DashboardWidgetDetailsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the dashboard widget details o k response
func (o *DashboardWidgetDetailsOK) SetPayload(payload *models.WidgetDetails) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DashboardWidgetDetailsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
DashboardWidgetDetailsDefault Generic error response.

swagger:response dashboardWidgetDetailsDefault
*/
type DashboardWidgetDetailsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewDashboardWidgetDetailsDefault creates DashboardWidgetDetailsDefault with default headers values
func NewDashboardWidgetDetailsDefault(code int) *DashboardWidgetDetailsDefault {
	if code <= 0 {
		code = 500
	}

	return &DashboardWidgetDetailsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the dashboard widget details default response
func (o *DashboardWidgetDetailsDefault) WithStatusCode(code int) *DashboardWidgetDetailsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the dashboard widget details default response
func (o *DashboardWidgetDetailsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the dashboard widget details default response
func (o *DashboardWidgetDetailsDefault) WithPayload(payload *models.APIError) *DashboardWidgetDetailsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the dashboard widget details default response
func (o *DashboardWidgetDetailsDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DashboardWidgetDetailsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
