// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openstor/console/models"
)

// GetUserPolicyHandlerFunc turns a function with the right signature into a get user policy handler
type GetUserPolicyHandlerFunc func(GetUserPolicyParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUserPolicyHandlerFunc) Handle(params GetUserPolicyParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetUserPolicyHandler interface for that can handle valid get user policy params
type GetUserPolicyHandler interface {
	Handle(GetUserPolicyParams, *models.Principal) middleware.Responder
}

// NewGetUserPolicy creates a new http.Handler for the get user policy operation
func NewGetUserPolicy(ctx *middleware.Context, handler GetUserPolicyHandler) *GetUserPolicy {
	return &GetUserPolicy{Context: ctx, Handler: handler}
}

/*
	GetUserPolicy swagger:route GET /user/policy Policy getUserPolicy

returns policies for logged in user
*/
type GetUserPolicy struct {
	Context *middleware.Context
	Handler GetUserPolicyHandler
}

func (o *GetUserPolicy) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetUserPolicyParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
