// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openstor/console/models"
)

// ListPoliciesOKCode is the HTTP code returned for type ListPoliciesOK
const ListPoliciesOKCode int = 200

/*
ListPoliciesOK A successful response.

swagger:response listPoliciesOK
*/
type ListPoliciesOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListPoliciesResponse `json:"body,omitempty"`
}

// NewListPoliciesOK creates ListPoliciesOK with default headers values
func NewListPoliciesOK() *ListPoliciesOK {

	return &ListPoliciesOK{}
}

// WithPayload adds the payload to the list policies o k response
func (o *ListPoliciesOK) WithPayload(payload *models.ListPoliciesResponse) *ListPoliciesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list policies o k response
func (o *ListPoliciesOK) SetPayload(payload *models.ListPoliciesResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListPoliciesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
ListPoliciesDefault Generic error response.

swagger:response listPoliciesDefault
*/
type ListPoliciesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewListPoliciesDefault creates ListPoliciesDefault with default headers values
func NewListPoliciesDefault(code int) *ListPoliciesDefault {
	if code <= 0 {
		code = 500
	}

	return &ListPoliciesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list policies default response
func (o *ListPoliciesDefault) WithStatusCode(code int) *ListPoliciesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list policies default response
func (o *ListPoliciesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list policies default response
func (o *ListPoliciesDefault) WithPayload(payload *models.APIError) *ListPoliciesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list policies default response
func (o *ListPoliciesDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListPoliciesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
