// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openstor/console/models"
)

// ListGroupsForPolicyOKCode is the HTTP code returned for type ListGroupsForPolicyOK
const ListGroupsForPolicyOKCode int = 200

/*
ListGroupsForPolicyOK A successful response.

swagger:response listGroupsForPolicyOK
*/
type ListGroupsForPolicyOK struct {

	/*
	  In: Body
	*/
	Payload []string `json:"body,omitempty"`
}

// NewListGroupsForPolicyOK creates ListGroupsForPolicyOK with default headers values
func NewListGroupsForPolicyOK() *ListGroupsForPolicyOK {

	return &ListGroupsForPolicyOK{}
}

// WithPayload adds the payload to the list groups for policy o k response
func (o *ListGroupsForPolicyOK) WithPayload(payload []string) *ListGroupsForPolicyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list groups for policy o k response
func (o *ListGroupsForPolicyOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListGroupsForPolicyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]string, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*
ListGroupsForPolicyDefault Generic error response.

swagger:response listGroupsForPolicyDefault
*/
type ListGroupsForPolicyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewListGroupsForPolicyDefault creates ListGroupsForPolicyDefault with default headers values
func NewListGroupsForPolicyDefault(code int) *ListGroupsForPolicyDefault {
	if code <= 0 {
		code = 500
	}

	return &ListGroupsForPolicyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list groups for policy default response
func (o *ListGroupsForPolicyDefault) WithStatusCode(code int) *ListGroupsForPolicyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list groups for policy default response
func (o *ListGroupsForPolicyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list groups for policy default response
func (o *ListGroupsForPolicyDefault) WithPayload(payload *models.APIError) *ListGroupsForPolicyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list groups for policy default response
func (o *ListGroupsForPolicyDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListGroupsForPolicyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
