// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openstor/console/models"
)

// ListGroupsForPolicyHandlerFunc turns a function with the right signature into a list groups for policy handler
type ListGroupsForPolicyHandlerFunc func(ListGroupsForPolicyParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn ListGroupsForPolicyHandlerFunc) Handle(params ListGroupsForPolicyParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// ListGroupsForPolicyHandler interface for that can handle valid list groups for policy params
type ListGroupsForPolicyHandler interface {
	Handle(ListGroupsForPolicyParams, *models.Principal) middleware.Responder
}

// NewListGroupsForPolicy creates a new http.Handler for the list groups for policy operation
func NewListGroupsForPolicy(ctx *middleware.Context, handler ListGroupsForPolicyHandler) *ListGroupsForPolicy {
	return &ListGroupsForPolicy{Context: ctx, Handler: handler}
}

/*
	ListGroupsForPolicy swagger:route GET /policies/{policy}/groups Policy listGroupsForPolicy

List Groups for a Policy
*/
type ListGroupsForPolicy struct {
	Context *middleware.Context
	Handler ListGroupsForPolicyHandler
}

func (o *ListGroupsForPolicy) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListGroupsForPolicyParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
