// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openstor/console/models"
)

// ListUsersForPolicyHandlerFunc turns a function with the right signature into a list users for policy handler
type ListUsersForPolicyHandlerFunc func(ListUsersForPolicyParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn ListUsersForPolicyHandlerFunc) Handle(params ListUsersForPolicyParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// ListUsersForPolicyHandler interface for that can handle valid list users for policy params
type ListUsersForPolicyHandler interface {
	Handle(ListUsersForPolicyParams, *models.Principal) middleware.Responder
}

// NewListUsersForPolicy creates a new http.Handler for the list users for policy operation
func NewListUsersForPolicy(ctx *middleware.Context, handler ListUsersForPolicyHandler) *ListUsersForPolicy {
	return &ListUsersForPolicy{Context: ctx, Handler: handler}
}

/*
	ListUsersForPolicy swagger:route GET /policies/{policy}/users Policy listUsersForPolicy

List Users for a Policy
*/
type ListUsersForPolicy struct {
	Context *middleware.Context
	Handler ListUsersForPolicyHandler
}

func (o *ListUsersForPolicy) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListUsersForPolicyParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
