// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openstor/console/models"
)

// SetPolicyMultipleHandlerFunc turns a function with the right signature into a set policy multiple handler
type SetPolicyMultipleHandlerFunc func(SetPolicyMultipleParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn SetPolicyMultipleHandlerFunc) Handle(params SetPolicyMultipleParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// SetPolicyMultipleHandler interface for that can handle valid set policy multiple params
type SetPolicyMultipleHandler interface {
	Handle(SetPolicyMultipleParams, *models.Principal) middleware.Responder
}

// NewSetPolicyMultiple creates a new http.Handler for the set policy multiple operation
func NewSetPolicyMultiple(ctx *middleware.Context, handler SetPolicyMultipleHandler) *SetPolicyMultiple {
	return &SetPolicyMultiple{Context: ctx, Handler: handler}
}

/*
	SetPolicyMultiple swagger:route PUT /set-policy-multi Policy setPolicyMultiple

Set policy to multiple users/groups
*/
type SetPolicyMultiple struct {
	Context *middleware.Context
	Handler SetPolicyMultipleHandler
}

func (o *SetPolicyMultiple) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSetPolicyMultipleParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
