// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package release

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openstor/console/models"
)

// ListReleasesHandlerFunc turns a function with the right signature into a list releases handler
type ListReleasesHandlerFunc func(ListReleasesParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn ListReleasesHandlerFunc) Handle(params ListReleasesParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// ListReleasesHandler interface for that can handle valid list releases params
type ListReleasesHandler interface {
	Handle(ListReleasesParams, *models.Principal) middleware.Responder
}

// NewListReleases creates a new http.Handler for the list releases operation
func NewListReleases(ctx *middleware.Context, handler ListReleasesHandler) *ListReleases {
	return &ListReleases{Context: ctx, Handler: handler}
}

/*
	ListReleases swagger:route GET /releases release listReleases

Get repo releases for a given version
*/
type ListReleases struct {
	Context *middleware.Context
	Handler ListReleasesHandler
}

func (o *ListReleases) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListReleasesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
