// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package service_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openstor/console/models"
)

// CreateServiceAccountCredsHandlerFunc turns a function with the right signature into a create service account creds handler
type CreateServiceAccountCredsHandlerFunc func(CreateServiceAccountCredsParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateServiceAccountCredsHandlerFunc) Handle(params CreateServiceAccountCredsParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// CreateServiceAccountCredsHandler interface for that can handle valid create service account creds params
type CreateServiceAccountCredsHandler interface {
	Handle(CreateServiceAccountCredsParams, *models.Principal) middleware.Responder
}

// NewCreateServiceAccountCreds creates a new http.Handler for the create service account creds operation
func NewCreateServiceAccountCreds(ctx *middleware.Context, handler CreateServiceAccountCredsHandler) *CreateServiceAccountCreds {
	return &CreateServiceAccountCreds{Context: ctx, Handler: handler}
}

/*
	CreateServiceAccountCreds swagger:route POST /service-account-credentials ServiceAccount createServiceAccountCreds

Create Service Account With Credentials
*/
type CreateServiceAccountCreds struct {
	Context *middleware.Context
	Handler CreateServiceAccountCredsHandler
}

func (o *CreateServiceAccountCreds) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateServiceAccountCredsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
