// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package service_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openstor/console/models"
)

// CreateServiceAccountCreatedCode is the HTTP code returned for type CreateServiceAccountCreated
const CreateServiceAccountCreatedCode int = 201

/*
CreateServiceAccountCreated A successful response.

swagger:response createServiceAccountCreated
*/
type CreateServiceAccountCreated struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceAccountCreds `json:"body,omitempty"`
}

// NewCreateServiceAccountCreated creates CreateServiceAccountCreated with default headers values
func NewCreateServiceAccountCreated() *CreateServiceAccountCreated {

	return &CreateServiceAccountCreated{}
}

// WithPayload adds the payload to the create service account created response
func (o *CreateServiceAccountCreated) WithPayload(payload *models.ServiceAccountCreds) *CreateServiceAccountCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create service account created response
func (o *CreateServiceAccountCreated) SetPayload(payload *models.ServiceAccountCreds) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateServiceAccountCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
CreateServiceAccountDefault Generic error response.

swagger:response createServiceAccountDefault
*/
type CreateServiceAccountDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewCreateServiceAccountDefault creates CreateServiceAccountDefault with default headers values
func NewCreateServiceAccountDefault(code int) *CreateServiceAccountDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateServiceAccountDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create service account default response
func (o *CreateServiceAccountDefault) WithStatusCode(code int) *CreateServiceAccountDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create service account default response
func (o *CreateServiceAccountDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create service account default response
func (o *CreateServiceAccountDefault) WithPayload(payload *models.APIError) *CreateServiceAccountDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create service account default response
func (o *CreateServiceAccountDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateServiceAccountDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
