// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package service_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openstor/console/models"
)

// DeleteMultipleServiceAccountsNoContentCode is the HTTP code returned for type DeleteMultipleServiceAccountsNoContent
const DeleteMultipleServiceAccountsNoContentCode int = 204

/*
DeleteMultipleServiceAccountsNoContent A successful response.

swagger:response deleteMultipleServiceAccountsNoContent
*/
type DeleteMultipleServiceAccountsNoContent struct {
}

// NewDeleteMultipleServiceAccountsNoContent creates DeleteMultipleServiceAccountsNoContent with default headers values
func NewDeleteMultipleServiceAccountsNoContent() *DeleteMultipleServiceAccountsNoContent {

	return &DeleteMultipleServiceAccountsNoContent{}
}

// WriteResponse to the client
func (o *DeleteMultipleServiceAccountsNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*
DeleteMultipleServiceAccountsDefault Generic error response.

swagger:response deleteMultipleServiceAccountsDefault
*/
type DeleteMultipleServiceAccountsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewDeleteMultipleServiceAccountsDefault creates DeleteMultipleServiceAccountsDefault with default headers values
func NewDeleteMultipleServiceAccountsDefault(code int) *DeleteMultipleServiceAccountsDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteMultipleServiceAccountsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete multiple service accounts default response
func (o *DeleteMultipleServiceAccountsDefault) WithStatusCode(code int) *DeleteMultipleServiceAccountsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete multiple service accounts default response
func (o *DeleteMultipleServiceAccountsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete multiple service accounts default response
func (o *DeleteMultipleServiceAccountsDefault) WithPayload(payload *models.APIError) *DeleteMultipleServiceAccountsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete multiple service accounts default response
func (o *DeleteMultipleServiceAccountsDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteMultipleServiceAccountsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
