// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AccountChangePasswordRequest account change password request
//
// swagger:model accountChangePasswordRequest
type AccountChangePasswordRequest struct {

	// current secret key
	// Required: true
	CurrentSecretKey *string `json:"current_secret_key"`

	// new secret key
	// Required: true
	NewSecretKey *string `json:"new_secret_key"`
}

// Validate validates this account change password request
func (m *AccountChangePasswordRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCurrentSecretKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNewSecretKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccountChangePasswordRequest) validateCurrentSecretKey(formats strfmt.Registry) error {

	if err := validate.Required("current_secret_key", "body", m.CurrentSecretKey); err != nil {
		return err
	}

	return nil
}

func (m *AccountChangePasswordRequest) validateNewSecretKey(formats strfmt.Registry) error {

	if err := validate.Required("new_secret_key", "body", m.NewSecretKey); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this account change password request based on context it is used
func (m *AccountChangePasswordRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AccountChangePasswordRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountChangePasswordRequest) UnmarshalBinary(b []byte) error {
	var res AccountChangePasswordRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
