// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BackendProperties backend properties
//
// swagger:model BackendProperties
type BackendProperties struct {

	// backend type
	BackendType string `json:"backendType,omitempty"`

	// offline drives
	OfflineDrives int64 `json:"offlineDrives,omitempty"`

	// online drives
	OnlineDrives int64 `json:"onlineDrives,omitempty"`

	// rr s c parity
	RrSCParity int64 `json:"rrSCParity,omitempty"`

	// standard s c parity
	StandardSCParity int64 `json:"standardSCParity,omitempty"`
}

// Validate validates this backend properties
func (m *BackendProperties) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this backend properties based on context it is used
func (m *BackendProperties) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BackendProperties) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BackendProperties) UnmarshalBinary(b []byte) error {
	var res BackendProperties
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
