// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// BucketEncryptionType bucket encryption type
//
// swagger:model bucketEncryptionType
type BucketEncryptionType string

func NewBucketEncryptionType(value BucketEncryptionType) *BucketEncryptionType {
	return &value
}

// Pointer returns a pointer to a freshly-allocated BucketEncryptionType.
func (m BucketEncryptionType) Pointer() *BucketEncryptionType {
	return &m
}

const (

	// BucketEncryptionTypeSseDashS3 captures enum value "sse-s3"
	BucketEncryptionTypeSseDashS3 BucketEncryptionType = "sse-s3"

	// BucketEncryptionTypeSseDashKms captures enum value "sse-kms"
	BucketEncryptionTypeSseDashKms BucketEncryptionType = "sse-kms"
)

// for schema
var bucketEncryptionTypeEnum []interface{}

func init() {
	var res []BucketEncryptionType
	if err := json.Unmarshal([]byte(`["sse-s3","sse-kms"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		bucketEncryptionTypeEnum = append(bucketEncryptionTypeEnum, v)
	}
}

func (m BucketEncryptionType) validateBucketEncryptionTypeEnum(path, location string, value BucketEncryptionType) error {
	if err := validate.EnumCase(path, location, value, bucketEncryptionTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this bucket encryption type
func (m BucketEncryptionType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateBucketEncryptionTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this bucket encryption type based on context it is used
func (m BucketEncryptionType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
