// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConfigExportResponse config export response
//
// swagger:model configExportResponse
type ConfigExportResponse struct {

	// status
	Status string `json:"status,omitempty"`

	// Returns base64 encoded value
	Value string `json:"value,omitempty"`
}

// Validate validates this config export response
func (m *ConfigExportResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this config export response based on context it is used
func (m *ConfigExportResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConfigExportResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigExportResponse) UnmarshalBinary(b []byte) error {
	var res ConfigExportResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
