// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EnvironmentConstants environment constants
//
// swagger:model environmentConstants
type EnvironmentConstants struct {

	// max concurrent downloads
	MaxConcurrentDownloads int64 `json:"maxConcurrentDownloads,omitempty"`

	// max concurrent uploads
	MaxConcurrentUploads int64 `json:"maxConcurrentUploads,omitempty"`
}

// Validate validates this environment constants
func (m *EnvironmentConstants) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this environment constants based on context it is used
func (m *EnvironmentConstants) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EnvironmentConstants) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EnvironmentConstants) UnmarshalBinary(b []byte) error {
	var res EnvironmentConstants
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
