// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IamPolicy iam policy
//
// swagger:model iamPolicy
type IamPolicy struct {

	// statement
	Statement []*IamPolicyStatement `json:"statement"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this iam policy
func (m *IamPolicy) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatement(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IamPolicy) validateStatement(formats strfmt.Registry) error {
	if swag.IsZero(m.Statement) { // not required
		return nil
	}

	for i := 0; i < len(m.Statement); i++ {
		if swag.IsZero(m.Statement[i]) { // not required
			continue
		}

		if m.Statement[i] != nil {
			if err := m.Statement[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("statement" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("statement" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this iam policy based on the context it is used
func (m *IamPolicy) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateStatement(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IamPolicy) contextValidateStatement(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Statement); i++ {

		if m.Statement[i] != nil {

			if swag.IsZero(m.Statement[i]) { // not required
				return nil
			}

			if err := m.Statement[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("statement" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("statement" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *IamPolicy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IamPolicy) UnmarshalBinary(b []byte) error {
	var res IamPolicy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
