// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ListGroupsResponse list groups response
//
// swagger:model listGroupsResponse
type ListGroupsResponse struct {

	// list of groups
	Groups []string `json:"groups"`

	// total number of groups
	Total int64 `json:"total,omitempty"`
}

// Validate validates this list groups response
func (m *ListGroupsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this list groups response based on context it is used
func (m *ListGroupsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ListGroupsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListGroupsResponse) UnmarshalBinary(b []byte) error {
	var res ListGroupsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
