// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NofiticationService nofitication service
//
// swagger:model nofiticationService
type NofiticationService string

func NewNofiticationService(value NofiticationService) *NofiticationService {
	return &value
}

// Pointer returns a pointer to a freshly-allocated NofiticationService.
func (m NofiticationService) Pointer() *NofiticationService {
	return &m
}

const (

	// NofiticationServiceWebhook captures enum value "webhook"
	NofiticationServiceWebhook NofiticationService = "webhook"

	// NofiticationServiceAmqp captures enum value "amqp"
	NofiticationServiceAmqp NofiticationService = "amqp"

	// NofiticationServiceKafka captures enum value "kafka"
	NofiticationServiceKafka NofiticationService = "kafka"

	// NofiticationServiceMqtt captures enum value "mqtt"
	NofiticationServiceMqtt NofiticationService = "mqtt"

	// NofiticationServiceNats captures enum value "nats"
	NofiticationServiceNats NofiticationService = "nats"

	// NofiticationServiceNsq captures enum value "nsq"
	NofiticationServiceNsq NofiticationService = "nsq"

	// NofiticationServiceMysql captures enum value "mysql"
	NofiticationServiceMysql NofiticationService = "mysql"

	// NofiticationServicePostgres captures enum value "postgres"
	NofiticationServicePostgres NofiticationService = "postgres"

	// NofiticationServiceElasticsearch captures enum value "elasticsearch"
	NofiticationServiceElasticsearch NofiticationService = "elasticsearch"

	// NofiticationServiceRedis captures enum value "redis"
	NofiticationServiceRedis NofiticationService = "redis"
)

// for schema
var nofiticationServiceEnum []interface{}

func init() {
	var res []NofiticationService
	if err := json.Unmarshal([]byte(`["webhook","amqp","kafka","mqtt","nats","nsq","mysql","postgres","elasticsearch","redis"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		nofiticationServiceEnum = append(nofiticationServiceEnum, v)
	}
}

func (m NofiticationService) validateNofiticationServiceEnum(path, location string, value NofiticationService) error {
	if err := validate.EnumCase(path, location, value, nofiticationServiceEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this nofitication service
func (m NofiticationService) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateNofiticationServiceEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this nofitication service based on context it is used
func (m NofiticationService) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
