// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NotificationEventType notification event type
//
// swagger:model notificationEventType
type NotificationEventType string

func NewNotificationEventType(value NotificationEventType) *NotificationEventType {
	return &value
}

// Pointer returns a pointer to a freshly-allocated NotificationEventType.
func (m NotificationEventType) Pointer() *NotificationEventType {
	return &m
}

const (

	// NotificationEventTypePut captures enum value "put"
	NotificationEventTypePut NotificationEventType = "put"

	// NotificationEventTypeDelete captures enum value "delete"
	NotificationEventTypeDelete NotificationEventType = "delete"

	// NotificationEventTypeGet captures enum value "get"
	NotificationEventTypeGet NotificationEventType = "get"

	// NotificationEventTypeReplica captures enum value "replica"
	NotificationEventTypeReplica NotificationEventType = "replica"

	// NotificationEventTypeIlm captures enum value "ilm"
	NotificationEventTypeIlm NotificationEventType = "ilm"

	// NotificationEventTypeScanner captures enum value "scanner"
	NotificationEventTypeScanner NotificationEventType = "scanner"
)

// for schema
var notificationEventTypeEnum []interface{}

func init() {
	var res []NotificationEventType
	if err := json.Unmarshal([]byte(`["put","delete","get","replica","ilm","scanner"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		notificationEventTypeEnum = append(notificationEventTypeEnum, v)
	}
}

func (m NotificationEventType) validateNotificationEventTypeEnum(path, location string, value NotificationEventType) error {
	if err := validate.EnumCase(path, location, value, notificationEventTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this notification event type
func (m NotificationEventType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateNotificationEventTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this notification event type based on context it is used
func (m NotificationEventType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
