// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// PolicyEntity policy entity
//
// swagger:model policyEntity
type PolicyEntity string

func NewPolicyEntity(value PolicyEntity) *PolicyEntity {
	return &value
}

// Pointer returns a pointer to a freshly-allocated PolicyEntity.
func (m PolicyEntity) Pointer() *PolicyEntity {
	return &m
}

const (

	// PolicyEntityUser captures enum value "user"
	PolicyEntityUser PolicyEntity = "user"

	// PolicyEntityGroup captures enum value "group"
	PolicyEntityGroup PolicyEntity = "group"
)

// for schema
var policyEntityEnum []interface{}

func init() {
	var res []PolicyEntity
	if err := json.Unmarshal([]byte(`["user","group"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		policyEntityEnum = append(policyEntityEnum, v)
	}
}

func (m PolicyEntity) validatePolicyEntityEnum(path, location string, value PolicyEntity) error {
	if err := validate.EnumCase(path, location, value, policyEntityEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this policy entity
func (m PolicyEntity) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validatePolicyEntityEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this policy entity based on context it is used
func (m PolicyEntity) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
