// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// SelectedSAs selected s as
//
// swagger:model selectedSAs
type SelectedSAs []string

// Validate validates this selected s as
func (m SelectedSAs) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this selected s as based on context it is used
func (m SelectedSAs) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
