// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceAccount service account
//
// swagger:model serviceAccount
type ServiceAccount struct {

	// account status
	AccountStatus string `json:"accountStatus,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// expiration
	Expiration string `json:"expiration,omitempty"`

	// implied policy
	ImpliedPolicy bool `json:"impliedPolicy,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// parent user
	ParentUser string `json:"parentUser,omitempty"`

	// policy
	Policy string `json:"policy,omitempty"`
}

// Validate validates this service account
func (m *ServiceAccount) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service account based on context it is used
func (m *ServiceAccount) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceAccount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceAccount) UnmarshalBinary(b []byte) error {
	var res ServiceAccount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
