// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SetConfigResponse set config response
//
// swagger:model setConfigResponse
type SetConfigResponse struct {

	// Returns wheter server needs to restart to apply changes or not
	Restart bool `json:"restart,omitempty"`
}

// Validate validates this set config response
func (m *SetConfigResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this set config response based on context it is used
func (m *SetConfigResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SetConfigResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SetConfigResponse) UnmarshalBinary(b []byte) error {
	var res SetConfigResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
