// SPDX-FileCopyrightText: 2025 openstor contributors
// SPDX-FileCopyrightText: 2015-2025 MinIO, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdateServiceAccountRequest update service account request
//
// swagger:model updateServiceAccountRequest
type UpdateServiceAccountRequest struct {

	// description
	Description string `json:"description,omitempty"`

	// expiry
	Expiry string `json:"expiry,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// policy
	// Required: true
	Policy *string `json:"policy"`

	// secret key
	SecretKey string `json:"secretKey,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this update service account request
func (m *UpdateServiceAccountRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePolicy(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateServiceAccountRequest) validatePolicy(formats strfmt.Registry) error {

	if err := validate.Required("policy", "body", m.Policy); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this update service account request based on context it is used
func (m *UpdateServiceAccountRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateServiceAccountRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateServiceAccountRequest) UnmarshalBinary(b []byte) error {
	var res UpdateServiceAccountRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
